### ISSUE TITLE
Add new image label or category

### ISSUE THREAD

**Issue by ResistanceIsUseless** [BishopFox/eyeballer#52]
How do I add my own image category or will you be expanding your list? I saw there was a request to make this modular but it's closed. While i agree there might not be a need for a huge list, you never know how the project could expand to include specific subsets such as a cms login vs myphpadmin login.  Depending on which way you decide to go it would be nice to point folks uneducated in TF  in the direction of how to modify and include their own or make it modular.

**Comment by dan-bishopfox** [comment]
You can just modify the list here:

https://github.com/BishopFox/eyeballer/blob/master/eyeballer/model.py#L20

Naturally, you'll also need to modify the training data CSV file to also contain the data labels for your new label, too.

The reason I closed that other ticket is because literally all it would do is move that single line of code to a separate file. It's not any more "modular", it's just more diffuse.
