### ISSUE TITLE
How to train new data for Eyeballer

### ISSUE THREAD

**Issue by tapilon** [BishopFox/eyeballer#59]
Hi there, I've used Eyewitness to gather some screenshots of a few websites and I have a folder called images that contains all the screenshots. What command should in order to train Eyeballer based on the new images that I am trying to feed it?

**Comment by dan-bishopfox** [comment]
In order to add new training data, you need to know ahead of time all the labels to all the images. You can't just take a pile of images and train against them without knowing where they belong. So you would need to go through (by hand) one-by-one and label every image. That's what the labels.csv file is that's in with the training data.

**Comment by tapilon** [comment]
Ah okay, I know that the CSV file is where I put the name of the image and its attributes. But in which folder should I put the image that has been linked to the CSV file?

**Comment by dan-bishopfox** [comment]
they go in a folder just named `images/` at the root of the project folder

**Comment by uBadRequest** [comment]
So it would make sense to just have folders that contain examples of each image category and just write a script to generate the labels.csv based on the folder that the images are in? Maybe then we can have a github repository where people can provide examples of images that can be placed into each category.

**Comment by dan-bishopfox** [comment]
No, that doesn't work since it's a multi-label problem. 

You can have an old-looking login page, for example. Images don't belong to just one category. So you can't group them nicely into folders. That's why the CSV is there, to keep track of the labels.

**Comment by uBadRequest** [comment]
> No, that doesn't work since it's a multi-label problem.
> 
> You can have an old-looking login page, for example. Images don't belong to just one category. So you can't group them nicely into folders. That's why the CSV is there, to keep track of the labels.

Ahh I ended up writing a script to do this. I created folders for each label and put all the images into the folders where the label was set to True. It made it easier to add new images, as I could just save new images into the folders that I was trying to create new labels for, then had a script go through the folders and add the new ones to the labels.csv file, based on the folder it was in, it would then set the column to true. I could save the same image into two folders, and it would set the column that the image was in to True.

**Comment by dan-bishopfox** [comment]
You _can_ do that. The trouble is that you're going to be training the model to learn that labels are mutually exclusive, when they aren't. To do it right, you really do need to go one-by-one and label each image for each category.

**Comment by uBadRequest** [comment]
By that you mean, an image having only 1 category assigned to it? right? If you put the same image into two of category folders, that image in the csv file would have those two labels set to true.

I was having trouble trying to train the model to detect screenshots of default webserver pages and pages that are simply just white pages with text at the top. Like text response from an API or some small error response. Maybe its because I didn't have enough training data? I keep thinking it might be easier to just do character recognition and find them that way rather then trying to do image recognition on them.

**Comment by dan-bishopfox** [comment]
If your problem can be solved by a regex, then it should be. :)

Eyeballer is really for high-level categories that are hard to write rules for. "Old Looking" is the perfect example of that.

**Comment by uBadRequest** [comment]
> If your problem can be solved by a regex, then it should be. :)
> 
> Eyeballer is really for high-level categories that are hard to write rules for. "Old Looking" is the perfect example of that.

My interest in Eyeballer was renewed after running [Natlas](https://github.com/natlas/natlas) for a few weeks and wanting to do something with the 10k screenshots i've collected so far. I think I might look into character recognition and have it look for specific words because currently Natlas doesn't save the HTTP responses.
