### ISSUE TITLE
Why did you choose the neural network architecture currently being used? 

### ISSUE THREAD

**Issue by c-flaherty** [BishopFox/eyeballer#62]
In particular,
1) Why does the current architecture downsample screenshots to (224, 224)? Did you find that the model is just as performant at such a low resolution? 
2) Why did you decide to use MobileNet (pre-trained on ImageNet) as opposed to other models that have performed better on ImageNet (and are also included in Keras) such as EfficientNet (any of the sizes) or Inception ResNet V2? Here is the link to the rankings for ImageNet, for convenience: https://paperswithcode.com/sota/image-classification-on-imagenet

**Comment by dan-bishopfox** [comment]
It's entirely possible that there's more optimal choices for ANY of the hyperparameters. I won't claim otherwise. :)

But in our testing, it worked really well and increasing the image size didn't seem to help. Though who knows, maybe with more (or just different) data it could be different. Definitely feel free to tinker with that.

**Comment by c-flaherty** [comment]
> It's entirely possible that there's more optimal choices for ANY of the hyperparameters. I won't claim otherwise. :)
> 
> But in our testing, it worked really well and increasing the image size didn't seem to help. Though who knows, maybe with more (or just different) data it could be different. Definitely feel free to tinker with that.

Got it, thank you for the context!
